
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build the project
      run: cargo build --release

    - name: Prepare SSH key
      run: |
        echo "${{secrets.SSH_PRIVATE_KEY}}" > deploy_key
        chmod 600 deploy_key
      shell: bash

    - name: Upload to VPS and restart service
      env:
        USER: root
        HOST: ${{ secrets.HOST }}
        SERVICE_NAME: geo-reader
      run: |
        echo "SERVICE_NAME: geo-reader"
        # Detener el servicio antes de la transferencia
        ssh -i deploy_key -o StrictHostKeyChecking=no $USER@$HOST 'sudo systemctl stop $SERVICE_NAME'
        # Subir el archivo
        scp -i deploy_key -o StrictHostKeyChecking=no target/release/geo-reader $USER@$HOST:/var/www/geo-reader/target/release/
        # Reiniciar el servicio
        ssh -i deploy_key -o StrictHostKeyChecking=no $USER@$HOST 'sudo systemctl start $SERVICE_NAME'
      shell: bash
